# site settings
title: Zack
subtitle: Wixom
email: zackwixom@gmail.com
description: Place to show my personal projects.
#baseurl: "/home" # the subpath of your site, e.g. /blog if using github pages (needed if hosting in a subdirectory) 
url: "https://z-wix.github.io" # the base hostname & protocol for your site
author: Zack Wixom
street_address: 1234 Somewhere Road
city: Lehi
state: UT
zip_code: 55555
country: United States of America
phone: (123) 456-7890
about-text: Senior Data Analyst that loves data and visualizations. I use R, Python, SQl, and Tableau.

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  email: zackwixom@gmail.com
  GitHub: https://github.com/z-wix
  Instagram: https://www.instagram.com/z.wixom/
  LinkedIn: https://www.linkedin.com/in/zackwixom/
  Twitch: https://www.twitch.tv/z_wix
  Spotify: https://open.spotify.com/user/zwixom?si=7cc9955c336c435a

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
